openapi: 3.0.3
info:
  description: KING OF TIME WebAPI specification https://developer.kingtime.jp/
  title: KING OF TIME WebAPI
  version: 1.0.0
servers:
- description: Production server (uses live data)
  url: https://api.kingtime.jp/v1.0
security:
- Bearer: []
tags:
- externalDocs:
    url: https://developer.kingtime.jp/#%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3
  name: Token
- externalDocs:
    url: https://developer.kingtime.jp/#%E4%BC%81%E6%A5%AD%E6%83%85%E5%A0%B1
  name: Company
- externalDocs:
    url: https://developer.kingtime.jp/#%E7%AE%A1%E7%90%86%E8%80%85
  name: Administrator
- externalDocs:
    url: https://developer.kingtime.jp/#%E5%BE%93%E6%A5%AD%E5%93%A1
  name: Employee
paths:
  /tokens/{token}:
    delete:
      description: 指定されたアクセストークンを利用停止する。
      externalDocs:
        url: https://developer.kingtime.jp/#%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3-%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3-delete
      operationId: SuspendAccessToken
      parameters:
      - description: 処理対象のトークン
        explode: false
        in: path
        name: token
        required: true
        schema:
          example: 8j9f7v4893y58rvt7nyfq2893n75tr78937n83
          type: string
        style: simple
      responses:
        "204":
          description: This response has no content.
      tags:
      - Token
    post:
      description: 指定されたアクセストークンを利用停止し、新たに同じ設定でアクセストークンを発行する。
      externalDocs:
        url: https://developer.kingtime.jp/#%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3-%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3-post
      operationId: RefreshAccessToken
      parameters:
      - description: 処理対象のトークン
        explode: false
        in: path
        name: token
        required: true
        schema:
          example: 8j9f7v4893y58rvt7nyfq2893n75tr78937n83
          type: string
        style: simple
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefreshAccessToken_201_response'
          description: ""
          headers:
            Content-Type:
              explode: false
              schema:
                example: application/json; charset=utf-8
                type: string
              style: simple
      tags:
      - Token
  /tokens/{token}/available:
    get:
      description: 指定されたアクセストークンが有効か確認する。
      externalDocs:
        url: https://developer.kingtime.jp/#%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3-%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3-get
      operationId: GetAccessTokenAvailability
      parameters:
      - description: 処理対象のトークン
        explode: false
        in: path
        name: token
        required: true
        schema:
          example: 8j9f7v4893y58rvt7nyfq2893n75tr78937n83
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccessTokenAvailability_200_response'
          description: ""
      tags:
      - Token
  /company:
    get:
      description: 企業情報データを取得する。
      externalDocs:
        description: 一覧
        url: https://developer.kingtime.jp/#%E4%BC%81%E6%A5%AD%E6%83%85%E5%A0%B1-%E4%BC%81%E6%A5%AD%E6%83%85%E5%A0%B1%E3%83%87%E3%83%BC%E3%82%BF-get
      operationId: GetCompany
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCompany_200_response'
          description: ""
          headers:
            Content-Type:
              explode: false
              schema:
                example: application/json
                type: string
              style: simple
      tags:
      - Company
  /administrators:
    get:
      description: 管理者のデータを取得する。
      externalDocs:
        description: 一覧
        url: https://developer.kingtime.jp/#%E7%AE%A1%E7%90%86%E8%80%85-%E7%AE%A1%E7%90%86%E8%80%85%E3%83%87%E3%83%BC%E3%82%BF-get
      operationId: GetAdministrators
      parameters:
      - description: 指定されたプロパティをレスポンスに追加
        explode: false
        in: query
        name: additionalFields
        required: false
        schema:
          example:
          - associatedEmployees
          items:
            enum:
            - emailAddresses
            - associatedEmployees
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                - code: admin
                  key: 4888a97dd7bbc6a26a18743f4697a1de4b38b6ee646a9620b286499c3df6918c
                  name: 全権管理者
                - code: "2000"
                  key: 6713cd21ca98689efec9fe27352152c4c77a34b32f5de30b6335d141ad714baf
                  name: エリアマネージャー
                  associatedEmployees:
                  - code: "1000"
                    key: 8b6ee646a9620b286499c3df6918c4888a97dd7bbc6a26a18743f4697a1de4b3
                    lastName: 勤怠
                    firstName: 太郎
                  - code: "2000"
                    key: c77a34b32f5de30b6335d141ad714baf6713cd21ca98689efec9fe27352152c4
                    lastName: 勤怠
                    firstName: 花子
                items:
                  $ref: '#/components/schemas/GetAdministrators_200_response_inner'
                type: array
          description: ""
          headers:
            Content-Type:
              explode: false
              schema:
                example: application/json
                type: string
              style: simple
      tags:
      - Administrator
  /employees:
    get:
      description: 従業員データの一覧を取得する。
      externalDocs:
        description: 一覧
        url: https://developer.kingtime.jp/#%E5%BE%93%E6%A5%AD%E5%93%A1-%E5%BE%93%E6%A5%AD%E5%93%A1%E3%83%87%E3%83%BC%E3%82%BF-get
      operationId: GetEmployees
      parameters:
      - description: |-
          指定された年月日時点での従業員のデータを表示
          ・過去日は最大3年前まで
          ・未来日は最大1年後まで
        explode: true
        in: query
        name: date
        required: false
        schema:
          description: defaultは当日
          format: date
          type: string
        style: form
      - description: 所属コード
        explode: true
        in: query
        name: division
        required: false
        schema:
          example: "1000"
          type: string
        style: form
      - description: 指定された年月日時点で退職済みの従業員を含む場合 True
        explode: true
        in: query
        name: includeResigner
        required: false
        schema:
          default: false
          example: true
          type: boolean
        style: form
      - description: 指定されたプロパティをレスポンスに追加
        explode: false
        in: query
        name: additionalFields
        required: false
        schema:
          example:
          - emailAddresses
          items:
            enum:
            - lastNamePhonetics
            - firstNamePhonetics
            - hiredDate
            - birthDate
            - resignationDate
            - emailAddresses
            - allDayRegardingWorkInMinute
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                - divisionCode: "1000"
                  divisionName: 本社
                  gender: male
                  typeCode: "1"
                  typeName: 正社員
                  code: "1000"
                  lastName: 勤怠
                  firstName: 太郎
                  key: 8b6ee646a9620b286499c3df6918c4888a97dd7bbc6a26a18743f4697a1de4b3
                  emailAddresses:
                  - kintaitarou@h-t.co.jp
                  employeeGroups:
                  - code: "0001"
                    name: 人事部
                  - code: "0002"
                    name: 総務部
                - divisionCode: "1000"
                  divisionName: 本社
                  gender: female
                  typeCode: "1"
                  typeName: 正社員
                  code: "2000"
                  lastName: 勤怠
                  firstName: 花子
                  key: c77a34b32f5de30b6335d141ad714baf6713cd21ca98689efec9fe27352152c4
                  emailAddresses:
                  - kintaihanako@h-t.co.jp
                  employeeGroups:
                  - code: "0003"
                    name: 営業部
                items:
                  $ref: '#/components/schemas/employee_response'
                type: array
          description: ""
          headers:
            Content-Type:
              explode: false
              schema:
                example: application/json
                type: string
              style: simple
      tags:
      - Employee
    post:
      description: 従業員のデータを登録する。(1件)
      externalDocs:
        description: 登録
        url: https://developer.kingtime.jp/#%E5%BE%93%E6%A5%AD%E5%93%A1-%E5%BE%93%E6%A5%AD%E5%93%A1%E3%83%87%E3%83%BC%E3%82%BF-post
      operationId: RegisterEmployee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/employee_request'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterEmployee_201_response'
          description: ""
          headers:
            Content-Type:
              explode: false
              schema:
                example: application/json
                type: string
              style: simple
      tags:
      - Employee
  /employees/{employeeCode}:
    get:
      description: 指定した従業員のデータを取得する。
      externalDocs:
        description: 従業員指定
        url: https://developer.kingtime.jp/#%E5%BE%93%E6%A5%AD%E5%93%A1-%E5%BE%93%E6%A5%AD%E5%93%A1%E3%83%87%E3%83%BC%E3%82%BF-get-1
      operationId: GetEmployee
      parameters:
      - description: 詳細を取得したい従業員コード
        explode: false
        in: path
        name: employeeCode
        required: true
        schema:
          example: "1000"
          type: string
        style: simple
      - description: |-
          指定された年月日時点での従業員のデータを表示
          ・過去日は最大3年前まで
          ・未来日は最大1年後まで
        explode: true
        in: query
        name: date
        required: false
        schema:
          description: defaultは当日
          format: date
          type: string
        style: form
      - description: 指定された年月日時点で退職済みの従業員を含む場合 True
        explode: true
        in: query
        name: includeResigner
        required: false
        schema:
          default: false
          example: true
          type: boolean
        style: form
      - description: 指定されたプロパティをレスポンスに追加
        explode: false
        in: query
        name: additionalFields
        required: false
        schema:
          example:
          - emailAddresses
          items:
            enum:
            - lastNamePhonetics
            - firstNamePhonetics
            - hiredDate
            - birthDate
            - resignationDate
            - emailAddresses
            - allDayRegardingWorkInMinute
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/employee_response'
          description: ""
          headers:
            Content-Type:
              explode: false
              schema:
                example: application/json
                type: string
              style: simple
      tags:
      - Employee
  /employees/{employeeKey}:
    put:
      description: |-
        従業員のデータを更新する。(1件)
        Request Bodyにて指定された項目のみ更新する。
        項目が指定され、値が無いまたは空文字列の場合は、該当項目をNULLで更新する。
        レスポンスには、AdditionalFieldを含むすべての従業員データを含める。
      externalDocs:
        description: 更新
        url: https://developer.kingtime.jp/#%E5%BE%93%E6%A5%AD%E5%93%A1-%E5%BE%93%E6%A5%AD%E5%93%A1%E3%83%87%E3%83%BC%E3%82%BF-put
      operationId: UpdateEmployee
      parameters:
      - description: 従業員識別キー（従業員コードが変更されても不変）
        explode: false
        in: path
        name: employeeKey
        required: true
        schema:
          example: 8b6ee646a9620b286499c3df6918c4888a97dd7bbc6a26a18743f4697a1de4b3
          type: string
        style: simple
      - description: 所属、雇用区分を更新したい年月日
        explode: true
        in: query
        name: updateDate
        required: false
        schema:
          description: defaultは当日
          format: date
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEmployee_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/employee_response'
          description: ""
          headers:
            Content-Type:
              explode: false
              schema:
                example: application/json
                type: string
              style: simple
      tags:
      - Employee
components:
  parameters:
    token:
      description: 処理対象のトークン
      explode: false
      in: path
      name: token
      required: true
      schema:
        example: 8j9f7v4893y58rvt7nyfq2893n75tr78937n83
        type: string
      style: simple
    additionalFields_administrator:
      description: 指定されたプロパティをレスポンスに追加
      explode: false
      in: query
      name: additionalFields
      required: false
      schema:
        example:
        - associatedEmployees
        items:
          enum:
          - emailAddresses
          - associatedEmployees
          type: string
        type: array
      style: form
    additionalFields_employee:
      description: 指定されたプロパティをレスポンスに追加
      explode: false
      in: query
      name: additionalFields
      required: false
      schema:
        example:
        - emailAddresses
        items:
          enum:
          - lastNamePhonetics
          - firstNamePhonetics
          - hiredDate
          - birthDate
          - resignationDate
          - emailAddresses
          - allDayRegardingWorkInMinute
          type: string
        type: array
      style: form
    date:
      description: |-
        指定された年月日時点での従業員のデータを表示
        ・過去日は最大3年前まで
        ・未来日は最大1年後まで
      explode: true
      in: query
      name: date
      required: false
      schema:
        description: defaultは当日
        format: date
        type: string
      style: form
    division:
      description: 所属コード
      explode: true
      in: query
      name: division
      required: false
      schema:
        example: "1000"
        type: string
      style: form
    includeResigner:
      description: 指定された年月日時点で退職済みの従業員を含む場合 True
      explode: true
      in: query
      name: includeResigner
      required: false
      schema:
        default: false
        example: true
        type: boolean
      style: form
    employeeCode:
      description: 詳細を取得したい従業員コード
      explode: false
      in: path
      name: employeeCode
      required: true
      schema:
        example: "1000"
        type: string
      style: simple
    employeeKey:
      description: 従業員識別キー（従業員コードが変更されても不変）
      explode: false
      in: path
      name: employeeKey
      required: true
      schema:
        example: 8b6ee646a9620b286499c3df6918c4888a97dd7bbc6a26a18743f4697a1de4b3
        type: string
      style: simple
    updateDate:
      description: 所属、雇用区分を更新したい年月日
      explode: true
      in: query
      name: updateDate
      required: false
      schema:
        description: defaultは当日
        format: date
        type: string
      style: form
  schemas:
    employee_response:
      example:
        lastName: lastName
        code: code
        gender: gender
        divisionName: divisionName
        typeName: typeName
        firstNamePhonetics: firstNamePhonetics
        allDayRegardingWorkInMinute: 480
        lastNamePhonetics: lastNamePhonetics
        birthDate: 2000-01-23
        resignationDate: 2000-01-23
        typeCode: typeCode
        divisionCode: divisionCode
        firstName: firstName
        emailAddresses:
        - emailAddresses
        - emailAddresses
        hiredDate: 2000-01-23
        key: key
        employeeGroups:
        - code: code
          name: name
        - code: code
          name: name
      properties:
        divisionCode:
          description: 所属コード
          type: string
        divisionName:
          description: 所属名
          type: string
        gender:
          description: 性別（male： 男性　female： 女性）
          type: string
        typeCode:
          description: 雇用区分コード
          type: string
        typeName:
          description: 雇用区分名
          type: string
        code:
          description: 従業員コード
          type: string
        key:
          description: 従業員識別キー（従業員コードが変更されても不変）
          type: string
        lastName:
          description: 姓
          type: string
        firstName:
          description: 名
          type: string
        employeeGroups:
          description: 従業員グループ情報
          items:
            $ref: '#/components/schemas/employee_response_employeeGroups_inner'
          type: array
        lastNamePhonetics:
          description: 姓（カナ）
          type: string
        firstNamePhonetics:
          description: 名（カナ）
          type: string
        hiredDate:
          description: 入社年月日
          format: date
          type: string
        birthDate:
          description: 生年月日
          format: date
          type: string
        resignationDate:
          description: 退職年月日
          format: date
          type: string
        emailAddresses:
          description: メールアドレス
          items:
            format: email
            type: string
          type: array
        allDayRegardingWorkInMinute:
          description: 日の契約労働時間
          example: 480
          type: integer
      required:
      - code
      - divisionCode
      - divisionName
      - employeeGroups
      - firstName
      - gender
      - key
      - lastName
      - typeCode
      - typeName
      type: object
    employee_request:
      properties:
        divisionCode:
          description: 所属コード
          type: string
        gender:
          description: 性別（male： 男性　female： 女性）
          type: string
        typeCode:
          description: 雇用区分コード
          type: string
        code:
          description: 従業員コード
          type: string
        lastName:
          description: 姓
          type: string
        firstName:
          description: 名
          type: string
        lastNamePhonetics:
          description: 姓（カナ）
          type: string
        firstNamePhonetics:
          description: 名（カナ）
          type: string
        hiredDate:
          description: 入社年月日
          format: date
          type: string
        birthDate:
          description: 生年月日
          format: date
          type: string
        resignationDate:
          description: 退職年月日
          format: date
          type: string
        emailAddresses:
          description: メールアドレス
          items:
            format: email
            type: string
          type: array
        allDayRegardingWorkInMinute:
          description: 日の契約労働時間
          example: 480
          type: integer
      required:
      - code
      - divisionCode
      - firstName
      - gender
      - lastName
      - typeCode
      type: object
    RefreshAccessToken_201_response:
      example:
        token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      properties:
        token:
          description: refreshed access token
          example: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          type: string
      required:
      - token
      type: object
    GetAccessTokenAvailability_200_response:
      example:
        available: true
      properties:
        available:
          type: boolean
      required:
      - available
      type: object
    GetCompany_200_response_settings:
      description: 企業設定情報
      properties:
        timeDisplayFormat:
          description: 表示形式（decimal： 10進法　sexagesimal： 60進法）
          type: string
        decimalTreatType:
          description: 10進表示の小数第3位の扱い（roundDown： 切下げ　roundUp： 切上げ　round： 四捨五入）
          type: string
      required:
      - decimalTreatType
      - timeDisplayFormat
      type: object
    GetCompany_200_response:
      example:
        key: 1qazxsw23edc....
        code: cmp
        name: 企業名
        host: s2.kingtime.jp
        businessYearStartDate: 04/01
        settings:
          timeDisplayFormat: decimal
          decimalTreatType: roundUp
      properties:
        key:
          description: 企業識別キー
          type: string
        code:
          description: 企業コード
          type: string
        name:
          description: 企業名
          type: string
        host:
          description: ホスト名
          type: string
        businessYearStartDate:
          description: 事業年度開始日
          type: string
        settings:
          $ref: '#/components/schemas/GetCompany_200_response_settings'
      required:
      - businessYearStartDate
      - code
      - host
      - key
      - name
      - settings
      type: object
    GetAdministrators_200_response_inner_associatedEmployees_inner:
      description: 割当従業員
      properties:
        code:
          description: 従業員コード
          type: string
        key:
          description: 従業員識別キー（従業員コードが変更されても不変）
          type: string
        lastName:
          description: 姓
          type: string
        firstName:
          description: 名
          type: string
      required:
      - code
      - firstName
      - key
      - lastName
      type: object
    GetAdministrators_200_response_inner:
      properties:
        code:
          description: 管理者コード
          type: string
        key:
          description: 管理者識別キー（管理者コードが変更されても不変）
          type: string
        name:
          description: 管理者名
          type: string
        emailAddresses:
          description: メールアドレス
          format: email
          type: string
        associatedEmployees:
          items:
            $ref: '#/components/schemas/GetAdministrators_200_response_inner_associatedEmployees_inner'
          type: array
      required:
      - code
      - key
      - name
      type: object
    RegisterEmployee_201_response:
      example:
        divisionCode: "1000"
        gender: male
        typeCode: "1"
        code: "1000"
        lastName: 勤怠
        firstName: 太郎
        key: c77a34b32f5de30b6335d141ad714baf6713cd21ca98689efec9fe27352152c4
        emailAddresses:
        - kintaitarou@h-t.co.jp
      properties:
        divisionCode:
          description: 所属コード
          type: string
        gender:
          description: 性別（male： 男性　female： 女性）
          type: string
        typeCode:
          description: 雇用区分コード
          type: string
        code:
          description: 従業員コード
          type: string
        lastName:
          description: 姓
          type: string
        firstName:
          description: 名
          type: string
        key:
          description: 従業員識別キー（従業員コードが変更されても不変）
          type: string
      required:
      - code
      - divisionCode
      - firstName
      - gender
      - key
      - lastName
      - typeCode
      type: object
    UpdateEmployee_request:
      example:
        divisionCode: "1000"
        gender: male
        typeCode: "1"
        code: "1000"
        lastName: 勤怠
        firstName: 太郎
        emailAddresses:
        - kintaitarou@h-t.co.jp
      properties:
        divisionCode:
          description: 所属コード
          type: string
        gender:
          description: 性別（male： 男性　female： 女性）
          type: string
        typeCode:
          description: 雇用区分コード
          type: string
        code:
          description: 従業員コード
          type: string
        lastName:
          description: 姓
          type: string
        firstName:
          description: 名
          type: string
        lastNamePhonetics:
          description: 姓（カナ）
          type: string
        firstNamePhonetics:
          description: 名（カナ）
          type: string
        hiredDate:
          description: 入社年月日
          format: date
          type: string
        birthDate:
          description: 生年月日
          format: date
          type: string
        resignationDate:
          description: 退職年月日
          format: date
          type: string
        emailAddresses:
          description: メールアドレス
          items:
            format: email
            type: string
          type: array
        allDayRegardingWorkInMinute:
          description: 日の契約労働時間
          example: 480
          type: integer
      type: object
    employee_response_employeeGroups_inner:
      example:
        code: code
        name: name
      properties:
        code:
          description: 従業員グループコード
          type: string
        name:
          description: 従業員グループ名
          type: string
      required:
      - code
      - name
      type: object
  securitySchemes:
    Bearer:
      description: Credentials or access token for API
      scheme: bearer
      type: http
